spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:h2:mem:codecard-local
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: localhost
    port: 25

jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci1sb2NhbC1kZXYtbWluaW11bS0yNTYtYml0cw==
